# This is the network config written by 'subiquity'
# network:
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [192.168.2.153/24]
      gateway4: 192.168.2.1
      nameservers:
        addresses: [192.168.2.1]
      routes:
      - to: 192.168.3.153/32
        via: 192.168.2.1
  version: 2
